repos:
  - repo: local
    hooks:
      - id: block-env-and-secrets
        name: Block .env and common secret patterns
        entry: python scripts/check_no_env.py
        language: system
        stages: [commit]
