#!/bin/bash
# GitHub Secrets Setup Helper for Enterprise IPO Reminder
# This script helps you set up the required GitHub secrets for the automated workflow

echo "🚀 ENTERPRISE IPO REMINDER - GITHUB SECRETS SETUP"
echo "=================================================="
echo ""
echo "This script will help you configure GitHub secrets for automated IPO reminders."
echo ""

# Check if we're in the right directory
if [ ! -f ".github/workflows/ipo-reminder.yml" ]; then
    echo "❌ Error: Please run this script from the ipo-reminder project root directory"
    exit 1
fi

echo "📋 REQUIRED GITHUB SECRETS:"
echo "==========================="
echo ""
echo "1. SENDER_EMAIL"
echo "   - Your Gmail address for sending IPO reminders"
echo "   - Example: your-email@gmail.com"
echo ""
echo "2. SENDER_PASSWORD"
echo "   - Gmail App Password (NOT your regular password)"
echo "   - Generate at: https://myaccount.google.com/apppasswords"
echo "   - Example: abcd-efgh-ijkl-mnop"
echo ""
echo "3. RECIPIENT_EMAIL"
echo "   - Email address that will receive IPO reminders"
echo "   - Can be the same as SENDER_EMAIL or different"
echo "   - Example: recipient@email.com"
echo ""
echo "4. OPTIONAL SECRETS (for enhanced features):"
echo "   - BSE_API_KEY: BSE API key for official data"
echo "   - NSE_API_KEY: NSE API key for official data"
echo "   - ENCRYPTION_KEY: Key for data encryption (auto-generated if not provided)"
echo "   - JWT_SECRET_KEY: Key for API authentication (auto-generated if not provided)"
echo ""

echo "🔧 HOW TO SET UP GITHUB SECRETS:"
echo "=================================="
echo ""
echo "1. Go to your GitHub repository: https://github.com/dilludinesh/ipo-reminder"
echo "2. Click on 'Settings' tab"
echo "3. Click on 'Secrets and variables' → 'Actions'"
echo "4. Click 'New repository secret'"
echo "5. Add each secret with the names and values shown above"
echo ""

echo "📧 GMAIL SETUP INSTRUCTIONS:"
echo "============================"
echo ""
echo "1. Enable 2-Factor Authentication on your Gmail account"
echo "2. Go to https://myaccount.google.com/apppasswords"
echo "3. Select 'Mail' and 'Other (custom name)'"
echo "4. Enter 'IPO Reminder' as the custom name"
echo "5. Copy the 16-character password"
echo "6. Use this password as SENDER_PASSWORD in GitHub secrets"
echo ""

echo "✅ VERIFICATION:"
echo "================"
echo ""
echo "After setting up secrets:"
echo "1. Go to Actions tab in your GitHub repository"
echo "2. Click on 'Enterprise IPO Reminder' workflow"
echo "3. Click 'Run workflow' to test manually"
echo "4. Check the workflow logs for any errors"
echo ""

echo "⏰ AUTOMATED SCHEDULE:"
echo "======================"
echo ""
echo "The workflow is configured to run:"
echo "• Daily at 9:00 AM IST (3:30 AM UTC)"
echo "• Can also be triggered manually from GitHub Actions"
echo "• Runs on every push to main branch (for testing)"
echo ""

echo "🔍 MONITORING:"
echo "=============="
echo ""
echo "• Check workflow status in GitHub Actions tab"
echo "• View detailed logs for each run"
echo "• Download log artifacts if needed"
echo "• Monitor email delivery and IPO data collection"
echo ""

echo "🎯 WHAT HAPPENS WHEN THE WORKFLOW RUNS:"
echo "========================================"
echo ""
echo "1. Sets up Python 3.11 environment"
echo "2. Installs all required dependencies"
echo "3. Starts PostgreSQL and Redis services"
echo "4. Initializes enterprise database"
echo "5. Fetches IPO data from multiple sources"
echo "6. Analyzes and categorizes IPOs"
echo "7. Generates professional HTML email"
echo "8. Sends IPO reminder email via Gmail"
echo "9. Logs all activities and saves to database"
echo "10. Cleans up resources"
echo ""

echo "📞 SUPPORT:"
echo "==========="
echo ""
echo "If you encounter issues:"
echo "1. Check the workflow logs in GitHub Actions"
echo "2. Verify all secrets are set correctly"
echo "3. Ensure Gmail App Password is valid"
echo "4. Check network connectivity for IPO data sources"
echo ""

echo "🎉 READY TO GO!"
echo "==============="
echo ""
echo "Once you've set up the GitHub secrets, your IPO reminder system will:"
echo "• Run automatically every day at 9:00 AM IST"
echo "• Send professional IPO reminder emails"
echo "• Store data in enterprise database"
echo "• Provide comprehensive monitoring and logging"
echo ""
echo "🏆 Your enterprise IPO reminder system is now completely automated on GitHub!"
echo ""

# Offer to test the setup
echo "🧪 Would you like to test the workflow locally first? (y/n)"
read -r test_local
if [[ $test_local =~ ^[Yy]$ ]]; then
    echo ""
    echo "Running local test..."
    ./run_enterprise_workflow.sh
fi
