name: IPO Reminder Bot

on:
  schedule:
    # Runs every day at 8:30 AM IST (which is 03:00 UTC)
    - cron: "30 3 * * *"
  workflow_dispatch: # allows manual run

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run IPO Reminder
        env:
          OUTLOOK_EMAIL: ${{ secrets.OUTLOOK_EMAIL }}
          OUTLOOK_APP_PASSWORD: ${{ secrets.OUTLOOK_APP_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          TENANT_ID: ${{ secrets.TENANT_ID }}
        run: |
          # Safety: fail if a .env file with secrets exists in the repository
          if [ -f .env ]; then
            echo ".env file found in repo. Exiting to avoid leaking secrets in CI." >&2
            exit 1
          fi
          python -m ipo_reminder.ipo_reminder
